import React, { useState } from "react";
import { stem, dlBlob, dlText, parsePageRange, esc } from "../lib/utils";
import { SHead, CCard, FZone, HInput, HSel, CStat, HBtn, Tip } from "./DocLensUI";

declare global {
  interface Window {
    pdfjsLib: any;
    JSZip: any;
    PDFLib: any;
    mammoth: any;
  }
}

export function ConvertPanel({ toast }: any) {
  const [st, setSt] = useState<any>({});
  const g = (k: string) => st[k] || {};
  const s = (k: string, v: any) => setSt((p: any) => ({ ...p, [k]: { ...p[k], ...v } }));
  async function run(key: string, fn: any) {
    s(key, { loading: true, status: "", statusType: "" });
    try {
      const msg = await fn();
      s(key, { loading: false, status: msg, statusType: "ok" });
      toast(msg);
    } catch (e: any) {
      s(key, { loading: false, status: e.message, statusType: "err" });
    }
  }
  const pdfjs = () => { window.pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js"; return window.pdfjsLib; };
  const ML = (files: any[], ico: string) => (files || []).length > 0 && (
    <div className="flex flex-col gap-[3px] max-h-[70px] overflow-y-auto">
      {files.map((f, i) => <div key={i} className="font-patrick text-[12px] text-ink3 bg-paper2 rounded-[2px_6px_3px_5px] py-[3px] px-[9px] whitespace-nowrap overflow-hidden text-ellipsis">{ico} {f.name}</div>)}
    </div>
  );

  const convFns = {
    pdfTxt: async () => { const f = g("pdfTxt").file; if (!f) return; await run("pdfTxt", async () => { const lib = pdfjs(), ab = await f.arrayBuffer(), pdf = await lib.getDocument({ data: ab }).promise; let t = ""; for (let i = 1; i <= pdf.numPages; i++) { const p = await pdf.getPage(i), c = await p.getTextContent(); t += `--- Page ${i} ---\n` + c.items.map((x: any) => x.str).join(" ") + "\n\n"; } dlText(stem(f.name) + ".txt", t.trim()); return `✓ ${pdf.numPages} pages extracted`; }); },
    pdfImg: async () => { const f = g("pdfImg").file; if (!f) return; const dpi = parseInt(g("pdfImg").dpi || "150") || 150; await run("pdfImg", async () => { const lib = pdfjs(), ab = await f.arrayBuffer(), pdf = await lib.getDocument({ data: ab }).promise, zip = new window.JSZip(); for (let i = 1; i <= pdf.numPages; i++) { const p = await pdf.getPage(i), vp = p.getViewport({ scale: dpi / 96 }), cv = document.createElement("canvas"); cv.width = vp.width; cv.height = vp.height; await p.render({ canvasContext: cv.getContext("2d"), viewport: vp }).promise; const bl: Blob = await new Promise((r: any) => cv.toBlob(r, "image/png")); zip.file(`page-${String(i).padStart(3, "0")}.png`, bl); s("pdfImg", { prog: Math.round(i / pdf.numPages * 100) }); } const zb = await zip.generateAsync({ type: "blob" }); dlBlob(stem(f.name) + "_images.zip", zb); return `✓ ${pdf.numPages} pages → ZIP`; }); },
    merge: async () => { const files = g("merge").files || []; if (files.length < 2) return; await run("merge", async () => { const { PDFDocument } = window.PDFLib, merged = await PDFDocument.create(); for (const f of files) { const ab = await f.arrayBuffer(), src = await PDFDocument.load(ab), pages = await merged.copyPages(src, src.getPageIndices()); pages.forEach((p: any) => merged.addPage(p)); } const bytes = await merged.save(); dlBlob("merged.pdf", new Blob([bytes], { type: "application/pdf" })); return `✓ ${files.length} PDFs merged`; }); },
    split: async () => { const f = g("split").file, ps = g("split").pages || ""; if (!f) return; await run("split", async () => { const { PDFDocument } = window.PDFLib, ab = await f.arrayBuffer(), src = await PDFDocument.load(ab), pages = parsePageRange(ps, src.getPageCount()); if (!pages.length) throw new Error("No valid pages"); const out = await PDFDocument.create(), copied = await out.copyPages(src, pages.map(p => p - 1)); copied.forEach((p: any) => out.addPage(p)); const bytes = await out.save(); dlBlob(stem(f.name) + "_split.pdf", new Blob([bytes], { type: "application/pdf" })); return `✓ ${pages.length} page(s) extracted`; }); },
    imgPdf: async () => { const files = g("imgPdf").files || []; if (!files.length) return; await run("imgPdf", async () => { const { PDFDocument } = window.PDFLib, pdf = await PDFDocument.create(); for (const f of files) { const ab = await f.arrayBuffer(); let img; if (f.type === "image/png") img = await pdf.embedPng(ab); else img = await pdf.embedJpg(ab); const page = pdf.addPage([img.width, img.height]); page.drawImage(img, { x: 0, y: 0, width: img.width, height: img.height }); } const bytes = await pdf.save(); dlBlob("images.pdf", new Blob([bytes], { type: "application/pdf" })); return `✓ ${files.length} images → PDF`; }); },
    rotate: async () => { const f = g("rotate").file; if (!f) return; const deg = parseInt(g("rotate").deg || "90"); await run("rotate", async () => { const { PDFDocument, degrees } = window.PDFLib, ab = await f.arrayBuffer(), pdf = await PDFDocument.load(ab); pdf.getPages().forEach((p: any) => { const c = p.getRotation().angle; p.setRotation(degrees((c + deg) % 360)); }); const bytes = await pdf.save(); dlBlob(stem(f.name) + "_rotated.pdf", new Blob([bytes], { type: "application/pdf" })); return `✓ Rotated ${deg}°`; }); },
    docxHtml: async () => { const f = g("docxHtml").file; if (!f) return; await run("docxHtml", async () => { const ab = await f.arrayBuffer(), r = await window.mammoth.convertToHtml({ arrayBuffer: ab }), html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Georgia,serif;max-width:820px;margin:44px auto;padding:0 28px;line-height:1.8;color:#1a1a1a}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccc;padding:9px}</style></head><body>${r.value}</body></html>`; dlText(stem(f.name) + ".html", html); return "✓ DOCX → HTML"; }); },
    docxTxt: async () => { const f = g("docxTxt").file; if (!f) return; await run("docxTxt", async () => { const ab = await f.arrayBuffer(), r = await window.mammoth.extractRawText({ arrayBuffer: ab }); dlText(stem(f.name) + ".txt", r.value); return "✓ Text extracted"; }); },
    docxMd: async () => { const f = g("docxMd").file; if (!f) return; await run("docxMd", async () => { const ab = await f.arrayBuffer(), r = await window.mammoth.convertToHtml({ arrayBuffer: ab }), md = r.value.replace(/<h1[^>]*>(.*?)<\/h1>/gi, "# $1\n").replace(/<h2[^>]*>(.*?)<\/h2>/gi, "## $1\n").replace(/<h3[^>]*>(.*?)<\/h3>/gi, "### $1\n").replace(/<strong[^>]*>(.*?)<\/strong>/gi, "**$1**").replace(/<em[^>]*>(.*?)<\/em>/gi, "*$1*").replace(/<li[^>]*>(.*?)<\/li>/gi, "- $1\n").replace(/<br\s*\/?>/gi, "\n").replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n\n").replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&nbsp;/g, " ").replace(/\n{3,}/g, "\n\n").trim(); dlText(stem(f.name) + ".md", md); return "✓ DOCX → Markdown"; }); },
    txtPdf: async () => { const f = g("txtPdf").file; if (!f) return; await run("txtPdf", async () => { const { PDFDocument, rgb } = window.PDFLib, text = await f.text(), pdf = await PDFDocument.create(), fs = 11, lh = 15, mg = 50, pw = 595, ph = 842, cpl = Math.floor((pw - mg * 2) / (fs * 0.55)), allLines: string[] = []; text.split("\n").forEach((line: string) => { if (!line.trim()) { allLines.push(""); return; } let l = line; while (l.length > cpl) { allLines.push(l.substring(0, cpl)); l = l.substring(cpl); } allLines.push(l); }); let page = pdf.addPage([pw, ph]), y = ph - mg; for (const line of allLines) { if (y < mg + lh) { page = pdf.addPage([pw, ph]); y = ph - mg; } if (line) page.drawText(line, { x: mg, y, size: fs, color: rgb(0.1, 0.1, 0.1) }); y -= lh; } const bytes = await pdf.save(); dlBlob(stem(f.name) + ".pdf", new Blob([bytes], { type: "application/pdf" })); return "✓ PDF created"; }); },
    csvHtml: async () => { const f = g("csvHtml").file; if (!f) return; await run("csvHtml", async () => { const text = await f.text(), rows = text.split("\n").map((r: string) => r.split(",").map((c: string) => c.replace(/^"|"$/g, "").trim())).filter((r: string[]) => r.some((c: string) => c)); if (!rows.length) throw new Error("Empty CSV"); const [header, ...body] = rows, html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:'Patrick Hand',cursive;padding:32px;background:#f7f0e3;color:#1c110a}h2{margin-bottom:20px;font-size:20px;font-family:'Caveat',cursive}table{border-collapse:collapse;width:100%;border-radius:8px;overflow:hidden}th{background:#1c110a;color:#f7f0e3;padding:11px 14px;text-align:left;font-size:14px}td{padding:10px 14px;border-bottom:1px solid #e3d8be;font-size:13px}tr:nth-child(even) td{background:#ede5d0}</style></head><body><h2>${esc(f.name)} — ${body.length} rows</h2><table><thead><tr>${header.map((h: string) => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${body.map((row: string[]) => `<tr>${row.map(c => `<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`; dlText(stem(f.name) + ".html", html); return `✓ ${body.length} rows converted`; }); },
  };

  const sections = [
    { ico: "📄", label: "PDF Conversions", cols: 2, cards: [
      { ico: "📄", title: "PDF → Plain Text", desc: "Extract all text, page by page", col: "#b02020", rot: 0.3, tip: "Saves a .txt with every page's text", body: <><FZone accept=".pdf" label="Drop a PDF here" file={g("pdfTxt").file} onFile={(f: File) => s("pdfTxt", { file: f })} tip="Click to browse or drag and drop a PDF" /><CStat msg={g("pdfTxt").status} type={g("pdfTxt").statusType} /><HBtn onClick={convFns.pdfTxt} disabled={!g("pdfTxt").file} loading={g("pdfTxt").loading} label="Convert & Download" tip="Extracts text from every page" /></> },
      { ico: "🖼️", title: "PDF → PNG Images", desc: "Render pages as images, zip download", col: "#1a5c5c", rot: -0.3, tip: "Each page becomes a PNG, bundled in a ZIP", body: <><FZone accept=".pdf" label="Drop a PDF here" file={g("pdfImg").file} onFile={(f: File) => s("pdfImg", { file: f })} tip="Click to browse or drag and drop a PDF" /><div className="flex gap-[8px] items-center"><HInput type="number" value={g("pdfImg").dpi || "150"} min="72" max="300" onChange={(e: any) => s("pdfImg", { dpi: e.target.value })} className="max-w-[80px]" /><Tip tip="Higher = sharper image, bigger file size"><span className="font-patrick text-[13px] text-ink4 cursor-help underline decoration-dotted decoration-[from-font]">DPI (72–300)</span></Tip></div>{g("pdfImg").loading && (g("pdfImg").prog || 0) > 0 && <div className="h-[5px] bg-paper3 rounded-[2px_6px] overflow-hidden border border-[rgba(100,70,40,.2)]"><div className="h-full bg-amber transition-[width] duration-300" style={{ width: (g("pdfImg").prog || 0) + "%" }} /></div>}<CStat msg={g("pdfImg").status} type={g("pdfImg").statusType} /><HBtn onClick={convFns.pdfImg} disabled={!g("pdfImg").file} loading={g("pdfImg").loading} label="Export as ZIP" tip="Creates page-001.png, page-002.png… in a ZIP" /></> },
      { ico: "🔗", title: "Merge PDFs", desc: "Stitch multiple PDFs into one", col: "#7a4510", rot: 0.2, tip: "Files are merged in the order you pick them", body: <><FZone accept=".pdf" label="Choose multiple PDFs" multi files={g("merge").files} onFiles={(f: File[]) => s("merge", { files: f })} tip="Hold Ctrl/Cmd to select multiple files" />{ML(g("merge").files, "📄")}<CStat msg={g("merge").status} type={g("merge").statusType} /><HBtn onClick={convFns.merge} disabled={!(g("merge").files?.length >= 2)} loading={g("merge").loading} label="Merge & Download" tip="You need at least 2 PDFs to merge" /></> },
      { ico: "✂️", title: "Split PDF", desc: "Pull out specific page ranges", col: "#1a5c5c", rot: -0.2, tip: 'Enter pages like "1-3, 5, 7" to extract', body: <><FZone accept=".pdf" label="Drop a PDF here" file={g("split").file} onFile={(f: File) => s("split", { file: f })} tip="The PDF you want to extract pages from" /><Tip tip='Examples: "1-3" · "2,4,6" · "1-3,7"'><HInput placeholder="Pages: 1-3, 5, 7" value={g("split").pages || ""} onChange={(e: any) => s("split", { pages: e.target.value })} /></Tip><CStat msg={g("split").status} type={g("split").statusType} /><HBtn onClick={convFns.split} disabled={!g("split").file || !g("split").pages} loading={g("split").loading} label="Extract Pages" tip="Saves only the pages you specified" /></> },
      { ico: "🖼️", title: "Images → PDF", desc: "Bundle JPG/PNG files into a PDF", col: "#1a3a6a", rot: 0.35, tip: "Images appear as full pages, in selection order", body: <><FZone accept="image/png,image/jpeg" label="Choose images (JPG/PNG)" multi files={g("imgPdf").files} onFiles={(f: File[]) => s("imgPdf", { files: f })} tip="Select multiple images at once" />{ML(g("imgPdf").files, "🖼️")}<CStat msg={g("imgPdf").status} type={g("imgPdf").statusType} /><HBtn onClick={convFns.imgPdf} disabled={!(g("imgPdf").files?.length > 0)} loading={g("imgPdf").loading} label="Create PDF" tip="Each image becomes one full page" /></> },
      { ico: "🔄", title: "Rotate PDF", desc: "Turn all pages 90°, 180°, or 270°", col: "#c07818", rot: -0.35, tip: "Rotation is applied to every page uniformly", body: <><FZone accept=".pdf" label="Drop a PDF here" file={g("rotate").file} onFile={(f: File) => s("rotate", { file: f })} tip="The PDF whose pages you want to rotate" /><Tip tip="Choose rotation angle for all pages"><HSel value={g("rotate").deg || "90"} onChange={(e: any) => s("rotate", { deg: e.target.value })}><option value="90">↩ Rotate 90° clockwise</option><option value="180">↕ Rotate 180°</option><option value="270">↪ Rotate 270° (counter-CW)</option></HSel></Tip><CStat msg={g("rotate").status} type={g("rotate").statusType} /><HBtn onClick={convFns.rotate} disabled={!g("rotate").file} loading={g("rotate").loading} label="Rotate & Download" tip="Applies to every page in the document" /></> },
    ] },
    { ico: "📝", label: "DOCX Conversions", cols: 3, cards: [
      { ico: "🌐", title: "DOCX → HTML", desc: "Word doc into a styled webpage", col: "#1a5c5c", rot: 0.3, tip: "Preserves headings, bold, italic, and tables", body: <><FZone accept=".docx" label="Drop a DOCX here" file={g("docxHtml").file} onFile={(f: File) => s("docxHtml", { file: f })} tip="Click to browse Word documents" /><CStat msg={g("docxHtml").status} type={g("docxHtml").statusType} /><HBtn onClick={convFns.docxHtml} disabled={!g("docxHtml").file} loading={g("docxHtml").loading} label="Convert & Download" tip="Downloads a self-contained .html file" /></> },
      { ico: "📄", title: "DOCX → TXT", desc: "Strip formatting, keep the text", col: "#5c1a1a", rot: -0.2, tip: "Plain text only — no bold, no structure", body: <><FZone accept=".docx" label="Drop a DOCX here" file={g("docxTxt").file} onFile={(f: File) => s("docxTxt", { file: f })} tip="Click to browse Word documents" /><CStat msg={g("docxTxt").status} type={g("docxTxt").statusType} /><HBtn onClick={convFns.docxTxt} disabled={!g("docxTxt").file} loading={g("docxTxt").loading} label="Convert & Download" tip="Saves a clean .txt file" /></> },
      { ico: "📑", title: "DOCX → Markdown", desc: "Word to clean .md format", col: "#1a3c7a", rot: 0.2, tip: "Headings and formatting become Markdown syntax", body: <><FZone accept=".docx" label="Drop a DOCX here" file={g("docxMd").file} onFile={(f: File) => s("docxMd", { file: f })} tip="Click to browse Word documents" /><CStat msg={g("docxMd").status} type={g("docxMd").statusType} /><HBtn onClick={convFns.docxMd} disabled={!g("docxMd").file} loading={g("docxMd").loading} label="Convert & Download" tip="Great for GitHub READMEs and note apps" /></> },
    ] },
    { ico: "✏️", label: "Text & Data", cols: 2, cards: [
      { ico: "📜", title: "TXT → PDF", desc: "Turn any text or Markdown into a PDF", col: "#5c1a1a", rot: 0.3, tip: "Long lines wrap automatically across pages", body: <><FZone accept=".txt,.md" label="Choose a TXT or MD file" file={g("txtPdf").file} onFile={(f: File) => s("txtPdf", { file: f })} tip="Plain text or Markdown files supported" /><CStat msg={g("txtPdf").status} type={g("txtPdf").statusType} /><HBtn onClick={convFns.txtPdf} disabled={!g("txtPdf").file} loading={g("txtPdf").loading} label="Create PDF" tip="Generates a clean A4 PDF from your text" /></> },
      { ico: "📊", title: "CSV → HTML Table", desc: "Spreadsheet data as a styled webpage", col: "#1a5c20", rot: -0.3, tip: "Builds a readable HTML page from any CSV", body: <><FZone accept=".csv" label="Choose a CSV file" file={g("csvHtml").file} onFile={(f: File) => s("csvHtml", { file: f })} tip="Standard comma-separated files only" /><CStat msg={g("csvHtml").status} type={g("csvHtml").statusType} /><HBtn onClick={convFns.csvHtml} disabled={!g("csvHtml").file} loading={g("csvHtml").loading} label="Convert & Download" tip="Downloads a styled, self-contained HTML table" /></> },
    ] },
  ];

  return (
    <div className="flex-1 overflow-y-auto py-[28px] px-[32px]">
      {sections.map(({ ico, label, cols, cards }) => (
        <div key={label} className="mb-[36px]">
          <SHead ico={ico} label={label} />
          <div className="grid gap-[16px]" style={{ gridTemplateColumns: `repeat(${cols}, 1fr)` }}>
            {cards.map(({ ico: ci, title, desc, col, rot, body, tip }) => (
              <Tip key={title} tip={tip} side="top">
                <CCard ico={ci} title={title} desc={desc} accentCol={col} rot={rot}>{body}</CCard>
              </Tip>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
